---

- name: "Include {{ ansible_os_family }} Specific Variables"
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install Dependancies
  package:
    name: "{{ librenms_agent__dependant_packages }}"
    state: present

- name: Setup snmp
  include_tasks: snmp.yml

- name: Setup check_mk
  include_tasks: check_mk.yml
  when: librenms_agent__agent_local_scripts is defined and ( librenms_agent__agent_local_scripts | length > 0 )

- name: Configure Scripts
  include_tasks: scripts/main.yml
