---
- name: Install Dependancies
  package:
    name: rsyslog
    state: present

- name: Configure snmp
  template:
    src: librenms.conf.j2
    dest: /etc/rsyslog.d/librenms.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart rsyslog

- name: Enable services
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: yes
