---

- name: Restart snmpd
  service:
    name: snmpd
    state: restarted

- name: Reload snmpd
  systemd:
    name: snmpd
    state: reloaded
    daemon_reload: true

- name: Restart check_mk
  service:
    name: check_mk.socket
    state: restarted

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted
