---

- name: Creates a cron file under /etc/cron.d
  cron:
    name: APT Update for SNMP os-updates
    minute: 0
    user: root
    job: "apt update >> /dev/null 2>&1"
    cron_file: 00__ansible-snmp
  when:
    - "'osupdate' in librenms_agent__snmp_scripts"
    - ansible_os_family == 'Debian'

- name: MySQL Script
  include_tasks: mysql.yml
  when: "'mysql' in librenms_agent__agent_local_scripts or 'mysql' in librenms_agent__snmp_scripts"

- name: Proxmox Script
  include_tasks: proxmox.yml
  when: "'proxmox' in librenms_agent__agent_local_scripts"

- name: Smart Script
  include_tasks: proxmox.yml
  when: "'smart' in librenms_agent__agent_snmp_scripts"
