---

- name: Install Dependancies for mysql script
  package:
    name: "{{ librenms_agent__scripts_mysql_packages }}"
    state: present

- name: MySQL Config snmp
  template:
    src: "scripts/mysql.cnf.j2"
    dest: "{{ librenms_agent__scripts_dir }}/mysql.cnf"
    owner: root
    group: root
    mode: 0644
  notify: Restart snmpd
