- name: Install smart dependency
  package:
    name: smartmontools
    state: present
  notify:
    - Restart snmpd

- name: Change the /etc/snmp/smart.config
  ansible.builtin.template:
    src: smart.config.j2
    dest: /etc/snmp/smart.config
  when:
    - librenms_agent__smart_devices is defined
  notify:
    - Restart snmpd
