- name: Install smart dependency
  package:
    name: smartmontools
    state: present
  notify:
    - Restart snmpd

- name: Change the /etc/snmp/smart.config
  ansible.builtin.template:
    src: scripts/smart.config.j2
    dest: /etc/snmp/scripts/smart.config
    owner: root
    group: root
    mode: 0644
  when:
    - librenms_agent__smart_devices is defined
  notify:
    - Restart snmpd
